validates:
  email_maximum: 140
  name_maximum: 140
  password_minimum: 6
remember_me_checked: 1
users:
  per_page: 10
gravatar_size: 80
gravatar_tiny_size: 40
gravatar_large_size: 180
gravatar_huge_size: 264
expired_time: 2
name_category_maximum: 50
description_minimum: 10
show: 10
room_image_mini_size: "80x60"
